version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./static:/workspace/static
      - ./templates:/workspace/templates
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
