version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-bot
    container_name: ai-bot-container
    ports:
      - "8181:8181"
    volumes:
      - .:/workspace
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
