version: '3.8'

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./data/chromadb:/chroma/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_HTTP_PORT=8000
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    ports:
      - "8080:8080"
    depends_on:
      chroma:
        condition: service_healthy
