version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    ports:
      - "8181:8181"
