version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-bot
    container_name: ai-bot-container
    ports:
      - "8181:8181"
    volumes:
      - .:/workspace
    restart: unless-stopped
    networks:
      - ai-network
    environment:
      - CHROMA_PERSISTANCE_PATH=~/
      - CHROMA_SERVER_HOST=http://52.37.221.188
      - CHROMA_SERVER_HTTP_PORT=8000
      - REDIS_HOST=redis-13571.c238.us-central1-2.gce.redns.redis-cloud.com
      - REDIS_PORT=13571
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=QzOWoUleui8jA2AKCdPjCYEXniqosWmX

networks:
  ai-network:
    driver: bridge
