name: Deploy to EC2

on:
  push:
    branches: [ deploy ]

env:
  CONTAINER_NAME: ai-bot
  EC2_HOST: ec2-52-37-221-188.us-west-2.compute.amazonaws.com
  EC2_USER: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker context for remote host
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem

    - name: Copy project files to EC2
      run: |
        scp -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no -r \
          ./* ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/app/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        CONTAINER_NAME: ai-bot
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: CONTAINER_NAME
        script: |
          cd ~/app
          docker ps -aq --filter "name=ai-bot" | grep -q . && docker stop ai-bot && docker rm ai-bot || true
          docker build -t ai-bot .
          docker run -d \
            --name ai-bot \
            -p 8181:8181 \
            -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            ai-bot