name: Deploy to EC2

on:
  push:
    branches: [ deploy ]

env:
  IMAGE_NAME: ai-bot
  EC2_HOST: ec2-52-37-221-188.us-west-2.compute.amazonaws.com
  EC2_USER: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .
        docker save ${{ env.IMAGE_NAME }} > image.tar

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Docker image to EC2
      run: |
        scp -i ~/.ssh/ec2.pem image.tar ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/image.tar

    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Load the new image
          docker load < ~/image.tar
          
          # Stop and remove existing container
          docker ps -q --filter "name=${{ env.IMAGE_NAME }}" | xargs -r docker stop
          docker ps -aq --filter "name=${{ env.IMAGE_NAME }}" | xargs -r docker rm
          
          # Run new container
          docker run -d \
            --name ${{ env.IMAGE_NAME }} \
            -p 8181:8181 \
            -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            ${{ env.IMAGE_NAME }}
          
          # Clean up
          rm ~/image.tar