name: Build and Deploy to EC2

on:
  push:
    branches:
      - multi_type_support

env:
  EC2_HOST: ec2-52-37-221-188.us-west-2.compute.amazonaws.com
  EC2_USER: ubuntu
  EC2_KEY: ${{ secrets.EC2_KEY }}
  EC2_DIR: ~/ai-bot/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker images using docker-compose
      run: |
        # Build the images with platform specification
        DOCKER_BUILDKIT=1 docker-compose build --build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETPLATFORM=linux/amd64
        # List images to verify they were built
        docker images
        # Pull the Chroma image explicitly
        docker pull chromadb/chroma:latest
        # Get the actual image names from docker-compose
        APP_IMAGE=$(docker-compose config | grep 'image:' | head -n1 | awk '{print $2}')
        # Tag images with platform-specific suffix
        docker tag $APP_IMAGE ${APP_IMAGE}-amd64
        docker tag chromadb/chroma:latest chromadb/chroma:latest-amd64

    - name: Save Docker images to tar
      run: |
        # Get app image name from docker-compose
        APP_IMAGE=$(docker-compose config | grep 'image:' | head -n1 | awk '{print $2}')
        # Save each built image to a tar file
        docker save -o app.tar $APP_IMAGE
        docker save -o chroma.tar chromadb/chroma:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

        # Copy the tar files to the EC2 instance
        scp -o StrictHostKeyChecking=no -i ec2_key.pem app.tar ${EC2_USER}@${EC2_HOST}:${EC2_DIR}/
        scp -o StrictHostKeyChecking=no -i ec2_key.pem chroma.tar ${EC2_USER}@${EC2_HOST}:${EC2_DIR}/

        # SSH into the EC2 instance and load the Docker images
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          # Load the Docker images from the tar files
          docker load -i ${EC2_DIR}/app.tar
          docker load -i ${EC2_DIR}/chroma.tar
          
          # Optionally, you can run the containers here
          # You might want to stop existing containers and remove them first
          docker-compose down
          docker-compose up -d
          
          # Clean up the tar files
          rm -f ${EC2_DIR}/app.tar
          rm -f ${EC2_DIR}/chroma.tar
        EOF
