name: Build and Deploy to EC2

on:
  push:
    branches:
      - multi_type_support

env:
  EC2_HOST: ec2-52-37-221-188.us-west-2.compute.amazonaws.com
  EC2_USER: ubuntu
  EC2_KEY: ${{ secrets.EC2_KEY }}
  EC2_DIR: ~/ai-bot/
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker images using docker-compose
      run: |
        # Build the images with platform specification
        DOCKER_BUILDKIT=1 docker-compose build --build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETPLATFORM=linux/amd64
        # List images to verify they were built
        docker images
        # Pull the Chroma image explicitly
        docker pull chromadb/chroma:latest
        # Get the actual image names from docker-compose
        APP_IMAGE=$(docker-compose config | grep 'image:' | head -n1 | awk '{print $2}')
        # Tag images with platform-specific suffix
        docker tag $APP_IMAGE ${APP_IMAGE}-amd64
        docker tag chromadb/chroma:latest chromadb/chroma:latest-amd64

    - name: Save and compress Docker images
      run: |
        # Get app image name from docker-compose
        APP_IMAGE=$(docker-compose config | grep 'image:' | head -n1 | awk '{print $2}')
        # Save and compress each image
        echo "Saving and compressing app image..."
        docker save $APP_IMAGE | gzip > app.tar.gz
        echo "Saving and compressing chroma image..."
        docker save chromadb/chroma:latest | gzip > chroma.tar.gz
        # Show file sizes
        ls -lh *.tar.gz

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        
        echo "Creating directory on EC2..."
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${EC2_HOST} "mkdir -p ${EC2_DIR}"

        echo "Copying app image to EC2..."
        scp -o StrictHostKeyChecking=no -i ec2_key.pem app.tar.gz ${EC2_USER}@${EC2_HOST}:${EC2_DIR}/
        echo "Copying chroma image to EC2..."
        scp -o StrictHostKeyChecking=no -i ec2_key.pem chroma.tar.gz ${EC2_USER}@${EC2_HOST}:${EC2_DIR}/

        echo "Loading images and starting containers on EC2..."
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${EC2_HOST} "
          cd ${EC2_DIR}
          echo 'Stopping existing containers...'
          docker-compose down || true
          
          echo 'Loading app image...'
          gunzip -c app.tar.gz | docker load
          echo 'Loading chroma image...'
          gunzip -c chroma.tar.gz | docker load
          
          echo 'Starting containers...'
          docker-compose up -d
          
          echo 'Cleaning up...'
          rm -f app.tar.gz chroma.tar.gz
          
          echo 'Checking container status...'
          docker ps
        "
